version: "3"
services:
  node:
    image: "node:18-alpine"
    user: "node"
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    volumes:
      - .:/app
    ports:
      - 5173:5173
    command: sh -c "npm install && npm start"
    stdin_open: true
    tty: true